import Navbar from "@/app/components/navbar/navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
        {children}
      </body>
    </html>
  )
}
